name: C++ CI with Qt (Docker - Reliable)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: rabits/qt:5.15-desktop
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install build dependencies
      run: |
        apt-get update -qq
        apt-get install -y --no-install-recommends \
          cmake \
          ninja-build \
          libgtest-dev \
          build-essential
    
    - name: Install Google Test
      run: |
        cd /usr/src/gtest
        cmake CMakeLists.txt
        make -j$(nproc)
        cp lib/*.a /usr/lib 2>/dev/null || cp *.a /usr/lib
    
    - name: Create build directory
      run: mkdir -p build
    
    - name: Configure CMake
      run: |
        cd build
        cmake -G Ninja \
              -DCMAKE_BUILD_TYPE=Release \
              ..
    
    - name: Build project
      run: |
        cd build
        ninja -j$(nproc)
    
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure --parallel $(nproc)
