name: C++ CI with Qt (qmake)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: ubuntu:20.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Qt and dependencies
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update -qq
        apt-get install -y --no-install-recommends \
          qt5-default \
          qtbase5-dev \
          qttools5-dev \
          qt5-qmake \
          g++ \
          build-essential \
          libgtest-dev
    
    - name: Install Google Test
      run: |
        cd /usr/src/gtest
        cmake CMakeLists.txt
        make -j$(nproc)
        cp lib/*.a /usr/lib 2>/dev/null || cp *.a /usr/lib
    
    - name: Build project with qmake
      run: |
        qmake *.pro
        make -j$(nproc)
    
    - name: Run tests (if you have test executable)
      run: |
        # Replace 'your_test_executable' with your actual test program name
        if [ -f ./tests ] || [ -f ./test ]; then
          ./tests || ./test
        else
          echo "No test executable found"
        fi

